### ISSUE TITLE
How to make links work?

### ISSUE THREAD

**Issue by hell4opt** [bmoliveira/MarkdownKit#43]
thx

**Comment by bmoliveira** [comment]
Hey, sorry for the delayed response.

Without more context I can't help much, can you provide a little more context? 

And have you tried out playing with the example project? I have a link to a raw markdown file and it contains links, if the links are broken I'll give it a look.

**Comment by hell4opt** [comment]
> Hey, sorry for the delayed response.
> 
> Without more context I can't help much, can you provide a little more context?
> 
> And have you tried out playing with the example project? I have a link to a raw markdown file and it contains links, if the links are broken I'll give it a look.

If you download your project and try to build it on the simulator, it will generate an error during the build, but I installed yours in the project, and when I clicked on the link, it does not open in safari

**Comment by bmoliveira** [comment]
Hey, I've just merged #45 because there was a problem of the bundle identifier of the example is the same as the library, now the example should run.

The links will open automatically if the link is a valid URL it will open the browser. For custom links, you need to build your handling of the links.
